// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DialogStateType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FTR.Core.Common.Protocol.RpcMessages {

  /// <summary>Holder for reflection information generated from DialogStateType.proto</summary>
  public static partial class DialogStateTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for DialogStateType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DialogStateTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVEaWFsb2dTdGF0ZVR5cGUucHJvdG8SCHByb3RvY29sKlwKD0RpYWxvZ1N0",
            "YXRlVHlwZRIXChNESUFMT0dfVFlQRV9TVEFSVEVEEAASGAoURElBTE9HX1RZ",
            "UEVfQURWQU5DRUQQARIWChJESUFMT0dfVFlQRV9DTE9TRUQQAkInqgIkRlRS",
            "LkNvcmUuQ29tbW9uLlByb3RvY29sLlJwY01lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum DialogStateType {
    [pbr::OriginalName("DIALOG_TYPE_STARTED")] DialogTypeStarted = 0,
    [pbr::OriginalName("DIALOG_TYPE_ADVANCED")] DialogTypeAdvanced = 1,
    [pbr::OriginalName("DIALOG_TYPE_CLOSED")] DialogTypeClosed = 2,
  }

  #endregion

}

#endregion Designer generated code
