// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InventoryErrorType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FTR.Core.Common.Protocol.RpcMessages {

  /// <summary>Holder for reflection information generated from InventoryErrorType.proto</summary>
  public static partial class InventoryErrorTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for InventoryErrorType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InventoryErrorTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhJbnZlbnRvcnlFcnJvclR5cGUucHJvdG8SCHByb3RvY29sKj8KEkludmVu",
            "dG9yeUVycm9yVHlwZRIUChBOT1RfRU5PVUdIX1NQQUNFEAASEwoPTk9UX0VO",
            "T1VHSF9HT0xEEAFCJ6oCJEZUUi5Db3JlLkNvbW1vbi5Qcm90b2NvbC5ScGNN",
            "ZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FTR.Core.Common.Protocol.RpcMessages.InventoryErrorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum InventoryErrorType {
    [pbr::OriginalName("NOT_ENOUGH_SPACE")] NotEnoughSpace = 0,
    [pbr::OriginalName("NOT_ENOUGH_GOLD")] NotEnoughGold = 1,
  }

  #endregion

}

#endregion Designer generated code
