// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StorageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FTR.Core.Common.Protocol.RpcMessages {

  /// <summary>Holder for reflection information generated from StorageType.proto</summary>
  public static partial class StorageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for StorageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StorageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTdG9yYWdlVHlwZS5wcm90bxIIcHJvdG9jb2wqXAoLU3RvcmFnZVR5cGUS",
            "FQoRU1RPUkFHRV9UWVBFX05VTEwQABIaChZTVE9SQUdFX1RZUEVfSU5WRU5U",
            "T1JZEAESGgoWU1RPUkFHRV9UWVBFX0ZBU1RfU0xPVBACQieqAiRGVFIuQ29y",
            "ZS5Db21tb24uUHJvdG9jb2wuUnBjTWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FTR.Core.Common.Protocol.RpcMessages.StorageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StorageType {
    [pbr::OriginalName("STORAGE_TYPE_NULL")] Null = 0,
    [pbr::OriginalName("STORAGE_TYPE_INVENTORY")] Inventory = 1,
    [pbr::OriginalName("STORAGE_TYPE_FAST_SLOT")] FastSlot = 2,
  }

  #endregion

}

#endregion Designer generated code
