// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events/DialogEventContent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FTR.Core.Common.Protocol.RpcMessages {

  /// <summary>Holder for reflection information generated from Events/DialogEventContent.proto</summary>
  public static partial class DialogEventContentReflection {

    #region Descriptor
    /// <summary>File descriptor for Events/DialogEventContent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DialogEventContentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9FdmVudHMvRGlhbG9nRXZlbnRDb250ZW50LnByb3RvEghwcm90b2NvbBoV",
            "RGlhbG9nU3RhdGVUeXBlLnByb3RvImsKEkRpYWxvZ0V2ZW50Q29udGVudBIv",
            "CgxkaWFsb2dfc3RhdGUYASABKA4yGS5wcm90b2NvbC5EaWFsb2dTdGF0ZVR5",
            "cGUSDgoGbnBjX2lkGAIgASgJEhQKDGRpYWxvZ19pbmRleBgDIAEoBUInqgIk",
            "RlRSLkNvcmUuQ29tbW9uLlByb3RvY29sLlJwY01lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FTR.Core.Common.Protocol.RpcMessages.DialogStateTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FTR.Core.Common.Protocol.RpcMessages.DialogEventContent), global::FTR.Core.Common.Protocol.RpcMessages.DialogEventContent.Parser, new[]{ "DialogState", "NpcId", "DialogIndex" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// DialogOpened=0, DialogAdvanced=1, DialogClosed=2.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DialogEventContent : pb::IMessage<DialogEventContent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DialogEventContent> _parser = new pb::MessageParser<DialogEventContent>(() => new DialogEventContent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DialogEventContent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FTR.Core.Common.Protocol.RpcMessages.DialogEventContentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogEventContent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogEventContent(DialogEventContent other) : this() {
      dialogState_ = other.dialogState_;
      npcId_ = other.npcId_;
      dialogIndex_ = other.dialogIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogEventContent Clone() {
      return new DialogEventContent(this);
    }

    /// <summary>Field number for the "dialog_state" field.</summary>
    public const int DialogStateFieldNumber = 1;
    private global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType dialogState_ = global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted;
    /// <summary>
    /// DialogState enum value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType DialogState {
      get { return dialogState_; }
      set {
        dialogState_ = value;
      }
    }

    /// <summary>Field number for the "npc_id" field.</summary>
    public const int NpcIdFieldNumber = 2;
    private string npcId_ = "";
    /// <summary>
    /// Empty when dialog_state = DialogClosed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NpcId {
      get { return npcId_; }
      set {
        npcId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dialog_index" field.</summary>
    public const int DialogIndexFieldNumber = 3;
    private int dialogIndex_;
    /// <summary>
    /// Ignored when dialog_state = DialogClosed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DialogIndex {
      get { return dialogIndex_; }
      set {
        dialogIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DialogEventContent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DialogEventContent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DialogState != other.DialogState) return false;
      if (NpcId != other.NpcId) return false;
      if (DialogIndex != other.DialogIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DialogState != global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted) hash ^= DialogState.GetHashCode();
      if (NpcId.Length != 0) hash ^= NpcId.GetHashCode();
      if (DialogIndex != 0) hash ^= DialogIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DialogState != global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DialogState);
      }
      if (NpcId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NpcId);
      }
      if (DialogIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DialogIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DialogState != global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DialogState);
      }
      if (NpcId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NpcId);
      }
      if (DialogIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DialogIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DialogState != global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DialogState);
      }
      if (NpcId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NpcId);
      }
      if (DialogIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DialogIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DialogEventContent other) {
      if (other == null) {
        return;
      }
      if (other.DialogState != global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType.DialogTypeStarted) {
        DialogState = other.DialogState;
      }
      if (other.NpcId.Length != 0) {
        NpcId = other.NpcId;
      }
      if (other.DialogIndex != 0) {
        DialogIndex = other.DialogIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DialogState = (global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType) input.ReadEnum();
            break;
          }
          case 18: {
            NpcId = input.ReadString();
            break;
          }
          case 24: {
            DialogIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DialogState = (global::FTR.Core.Common.Protocol.RpcMessages.DialogStateType) input.ReadEnum();
            break;
          }
          case 18: {
            NpcId = input.ReadString();
            break;
          }
          case 24: {
            DialogIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
