// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events/InitialForceEventContent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FTR.Core.Common.Protocol.RpcMessages {

  /// <summary>Holder for reflection information generated from Events/InitialForceEventContent.proto</summary>
  public static partial class InitialForceEventContentReflection {

    #region Descriptor
    /// <summary>File descriptor for Events/InitialForceEventContent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InitialForceEventContentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVFdmVudHMvSW5pdGlhbEZvcmNlRXZlbnRDb250ZW50LnByb3RvEghwcm90",
            "b2NvbBoSUHJvdG9WZWN0b3IzLnByb3RvInMKGEluaXRpYWxGb3JjZUV2ZW50",
            "Q29udGVudBIlCgVmb3JjZRgBIAEoCzIWLnByb3RvY29sLlByb3RvVmVjdG9y",
            "MxIwChBpbml0aWFsX3Bvc2l0aW9uGAIgASgLMhYucHJvdG9jb2wuUHJvdG9W",
            "ZWN0b3IzQieqAiRGVFIuQ29yZS5Db21tb24uUHJvdG9jb2wuUnBjTWVzc2Fn",
            "ZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FTR.Core.Common.Protocol.RpcMessages.InitialForceEventContent), global::FTR.Core.Common.Protocol.RpcMessages.InitialForceEventContent.Parser, new[]{ "Force", "InitialPosition" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InitialForceEventContent : pb::IMessage<InitialForceEventContent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitialForceEventContent> _parser = new pb::MessageParser<InitialForceEventContent>(() => new InitialForceEventContent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitialForceEventContent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FTR.Core.Common.Protocol.RpcMessages.InitialForceEventContentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialForceEventContent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialForceEventContent(InitialForceEventContent other) : this() {
      force_ = other.force_ != null ? other.force_.Clone() : null;
      initialPosition_ = other.initialPosition_ != null ? other.initialPosition_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialForceEventContent Clone() {
      return new InitialForceEventContent(this);
    }

    /// <summary>Field number for the "force" field.</summary>
    public const int ForceFieldNumber = 1;
    private global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3 force_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3 Force {
      get { return force_; }
      set {
        force_ = value;
      }
    }

    /// <summary>Field number for the "initial_position" field.</summary>
    public const int InitialPositionFieldNumber = 2;
    private global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3 initialPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3 InitialPosition {
      get { return initialPosition_; }
      set {
        initialPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitialForceEventContent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitialForceEventContent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Force, other.Force)) return false;
      if (!object.Equals(InitialPosition, other.InitialPosition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (force_ != null) hash ^= Force.GetHashCode();
      if (initialPosition_ != null) hash ^= InitialPosition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (force_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Force);
      }
      if (initialPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InitialPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (force_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Force);
      }
      if (initialPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InitialPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (force_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Force);
      }
      if (initialPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitialPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitialForceEventContent other) {
      if (other == null) {
        return;
      }
      if (other.force_ != null) {
        if (force_ == null) {
          Force = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
        }
        Force.MergeFrom(other.Force);
      }
      if (other.initialPosition_ != null) {
        if (initialPosition_ == null) {
          InitialPosition = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
        }
        InitialPosition.MergeFrom(other.InitialPosition);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (force_ == null) {
              Force = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
            }
            input.ReadMessage(Force);
            break;
          }
          case 18: {
            if (initialPosition_ == null) {
              InitialPosition = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
            }
            input.ReadMessage(InitialPosition);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (force_ == null) {
              Force = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
            }
            input.ReadMessage(Force);
            break;
          }
          case 18: {
            if (initialPosition_ == null) {
              InitialPosition = new global::FTR.Core.Common.Protocol.RpcMessages.ProtoVector3();
            }
            input.ReadMessage(InitialPosition);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
