services:
  ftr-server:
    profiles: ["all"]
    env_file:
      - .env
    build:
      context: .
    command: [
      "-batchmode",
      "-nographics",
      "--world-id=${WORLD_ID}",
      "--zone-id=${ZONE_ID}"
    ]
    network_mode: host # Assumes core-service running on localhost:8000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./local_buckets:/usr/src/app/local_buckets

  mongo: # For local ftr-servers persistance (game)
    command: ["--quiet", "--logpath", "/dev/null"]
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
