services:
  ftr-server:
    profiles: ["all"]
    environment:
      MONGO_CONNECTION_STRING: "mongodb://admin:admin@mongo/?authSource=admin"
    build:
      context: .
    command: ["--world-id", "1", "--zone-id", "1"]
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./local_buckets:/usr/src/app/local_buckets
    networks:
      - dev-app-network

  mongo: # For local ftr-servers persistance (game)
    command: ["--quiet", "--logpath", "/dev/null"]
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dev-app-network:
    driver: bridge

volumes:
  mongo_data:
