---
name: Build
on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      ECR_REGISTRY:
        required: true
      ECR_REPOSITORY:
        required: true

permissions:
  contents: read
  packages: read

env:
  GHCR: ghcr.io/${{ github.repository_owner }}
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - name: Extract tag
        id: tag
        run: |
          echo "image_tag=ftr-server:${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "Tag extracted: $image_tag"

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull image from GHCR
        run: |
          docker pull $GHCR/${{ steps.tag.outputs.image_tag }}

      - name: List images
        run: docker images

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2

      - name: Tag image for ECR
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}"
          IMAGE_URI="${IMAGE_URI}:${TAG}"
          docker tag "$GHCR/${{ steps.tag.outputs.image_tag }}" "$IMAGE_URI"

      - name: Build & Push
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}"
          IMAGE_URI="${IMAGE_URI}:${TAG}"
          docker push "$IMAGE_URI"
