---
name: CI/CD
"on":
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      INSTANCE_IDS: ${{ secrets.INSTANCE_IDS }}
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
