name: CI/CD
on:
  push:
    tags:
      - "v*-server"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      WEBHOOK_AUDIENCE: ${{ secrets.WEBHOOK_AUDIENCE }}
      WEBHOOK_BASE_URL: ${{ secrets.WEBHOOK_BASE_URL }}
