---
name: Deploy
on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      ECR_REGISTRY:
        required: true
      ECR_REPOSITORY:
        required: true
      INSTANCE_IDS:
        required: true
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Hello world
        run: >
          echo "Hello world! The image tag is
          ${{ inputs.image_tag }}"
        # - name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v4
        #   with:
        #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        #     aws-region: ${{ secrets.AWS_REGION }}
        # - name: Deploy core-service via SSM
        #   run: |
        #     aws ssm send-command \
        #       --document-name "AWS-RunShellScript" \
        #       --instance-ids ${{ secrets.INSTANCE_IDS }} \
        #       --comment "Deploy core-service" \
        #       --parameters '{"commands": [
        #         "set -e",
        #         "SERVICE=core-service",
        #         "IMAGE=${{ secrets.ECR_REGISTRY }}/
        #         ${{ secrets.ECR_REPOSITORY }}:
        #         ${{ inputs.image_tag }}",
        #         "aws ecr get-login-password
        #         --region ${{ secrets.AWS_REGION }} |
        #         docker login --username AWS
        #         --password-stdin ${{ secrets.ECR_REGISTRY }}",
        #         "docker stop $SERVICE || true",
        #         "docker rm $SERVICE || true",
        #         "docker rmi $(docker images -q) || true",
        #         "docker pull $IMAGE",
        #         "aws ssm get-parameters-by-path
        #         --path \"/core-service/\"
        #         --with-decryption
        #         --region ${{ secrets.AWS_REGION }}
        #         --query \"Parameters[*].[Name,Value]\"
        #         --output text | sed
        #         \"s#/core-service/##g; s#\\t#=#g\"
        #         > /tmp/core_service_env",
        #         "docker run -d --restart always
        #         --name $SERVICE -p 34782:8000
        #         --env-file /tmp/core_service_env $IMAGE",
        #         "rm /tmp/core_service_env"
        #       ]}'
